I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 549, in script
    show son at topright with disoslve
  File "game/script.rpy", line 549, in <module>
    show son at topright with disoslve
NameError: name 'disoslve' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 549, in script
    show son at topright with disoslve
  File "C:\Users\Usuario\Documents\Renpy\renpy\ast.py", line 1654, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\Usuario\Documents\Renpy\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Usuario\Documents\Renpy\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 549, in <module>
    show son at topright with disoslve
NameError: name 'disoslve' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
The Working Woman's Guide to Burning Bridges 1.0
Thu Jun 29 10:50:40 2023
