I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1533, in script
    $ goodChoiceAlex+=1
  File "game/script.rpy", line 1533, in <module>
    $ goodChoiceAlex+=1
NameError: name 'goodChoiceAlex' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1533, in script
    $ goodChoiceAlex+=1
  File "C:\Users\Usuario\Documents\Renpy\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Usuario\Documents\Renpy\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 1533, in <module>
    $ goodChoiceAlex+=1
NameError: name 'goodChoiceAlex' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
The Working Woman's Guide to Burning Bridges 1.0
Thu Jun 29 23:43:28 2023
